//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningEntity.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetai
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int InstructorId { get; set; }
        public int SupportId { get; set; }
        public int CourseCode { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Support Support { get; set; }
    }
}
