//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningEntity.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetaild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileDetaild()
        {
            this.Supports = new HashSet<Support>();
        }
    
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int InstructorId { get; set; }
        public int SupportId { get; set; }
        public int CourseCode { get; set; }
        public Nullable<int> Support_SupportId { get; set; }
        public Nullable<int> Support_SupportId1 { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Support Support { get; set; }
        public virtual Support Support1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Support> Supports { get; set; }
    }
}
